/**
 * `.agent/` configuration loader — read-only behavior, no policy logic.
 *
 * Loads the three `.agent/` files, validates them against the TypeBox schemas, and
 * synthesizes defaults for anything missing. It NEVER throws: a missing or invalid
 * file degrades to defaults plus a diagnostic, leaving the caller to decide what to do.
 *
 * Validation uses the compiled-validator pattern from `typebox/compile`
 * (`Compile(schema).Check()/.Errors()`) — the same path pi's own runtime uses for
 * tool-arg validation (packages/ai/src/utils/validation.ts). Defaults are applied by
 * deep-merging over a hand-written `DEFAULT_POLICY_CONFIG`, which also lets a partial
 * `policy.json` fill in the rest.
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { Compile } from "typebox/compile";
import {
	DEFAULT_PATH_CONFIRM_WRITE_PATTERNS,
	DEFAULT_PATH_DENY_PATTERNS,
	DEFAULT_POLICY_ALLOW_PATTERNS,
	DEFAULT_POLICY_CONFIRM_PATTERNS,
	DEFAULT_POLICY_DENY_PATTERNS,
} from "../policy/types.ts";
import { type PolicyConfig, PolicyConfigSchema, type ProjectProfile, ProjectProfileSchema } from "./schema.ts";

export const policyValidator = Compile(PolicyConfigSchema);

export const DEFAULT_POLICY_CONFIG: PolicyConfig = {
	command: {
		allow: DEFAULT_POLICY_ALLOW_PATTERNS,
		confirm: DEFAULT_POLICY_CONFIRM_PATTERNS,
		deny: DEFAULT_POLICY_DENY_PATTERNS,
	},
	path: { deny: DEFAULT_PATH_DENY_PATTERNS, confirmWrite: DEFAULT_PATH_CONFIRM_WRITE_PATTERNS },
	limits: { maxChangedFiles: 20, maxFixIterations: 5, maxToolCalls: 50, commandTimeoutMs: 120_000 },
	sandbox: { enabled: false },
};

export interface ConfigDiagnostic {
	file: string;
	level: "warn" | "error";
	message: string;
}

export interface AgentConfig {
	policy: PolicyConfig;
	profile: ProjectProfile | null;
	memory: string;
	diagnostics: ConfigDiagnostic[];
}

export function agentDir(cwd: string): string {
	return join(cwd, ".agent");
}

function readJson(path: string): { ok: true; value: unknown } | { ok: false; error: string } {
	try {
		return { ok: true, value: JSON.parse(readFileSync(path, "utf8")) };
	} catch (err) {
		return { ok: false, error: err instanceof Error ? err.message : String(err) };
	}
}

function formatErrors(
	validator: { Errors(value: unknown): Iterable<{ instancePath?: string; message?: string }> },
	value: unknown,
): string {
	return [...validator.Errors(value)].map((e) => `${e.instancePath ?? "/"}: ${e.message ?? "invalid"}`).join("; ");
}

function mergePolicy(base: PolicyConfig, override: unknown): PolicyConfig {
	const o = (override ?? {}) as Record<string, Record<string, unknown> | undefined>;
	const command = o.command ?? {};
	const path = o.path ?? {};
	const limits = o.limits ?? {};
	const sandbox = o.sandbox ?? {};
	return {
		command: {
			allow: (command.allow as string[]) ?? base.command.allow,
			confirm: (command.confirm as string[]) ?? base.command.confirm,
			deny: (command.deny as string[]) ?? base.command.deny,
		},
		path: {
			deny: (path.deny as string[]) ?? base.path.deny,
			confirmWrite: (path.confirmWrite as string[]) ?? base.path.confirmWrite,
		},
		limits: {
			maxChangedFiles: (limits.maxChangedFiles as number) ?? base.limits.maxChangedFiles,
			maxFixIterations: (limits.maxFixIterations as number) ?? base.limits.maxFixIterations,
			maxToolCalls: (limits.maxToolCalls as number) ?? base.limits.maxToolCalls,
			tokenBudget: (limits.tokenBudget as number | undefined) ?? base.limits.tokenBudget,
			commandTimeoutMs: (limits.commandTimeoutMs as number | undefined) ?? base.limits.commandTimeoutMs,
		},
		sandbox: {
			enabled: (sandbox.enabled as boolean) ?? base.sandbox.enabled,
		},
	};
}

/**
 * Lightweight structural check: a profile must have `language` and `packageManager`
 * at minimum. We avoid `Compile().Check()` here because project-profile.json is
 * generated by `agent init` (not edited by hand), so a structural guard suffices.
 */
function isProfileLike(value: unknown): boolean {
	const o = value as Record<string, unknown> | null;
	return typeof o?.language === "string" && typeof o?.packageManager === "string";
}

export function loadAgentConfig(cwd: string): AgentConfig {
	const dir = agentDir(cwd);
	const diagnostics: ConfigDiagnostic[] = [];

	// --- policy.json ---
	let policy: PolicyConfig = structuredClone(DEFAULT_POLICY_CONFIG);
	const policyPath = join(dir, "policy.json");
	if (!existsSync(policyPath)) {
		diagnostics.push({ file: policyPath, level: "warn", message: "缺失,使用默认 policy" });
	} else {
		const parsed = readJson(policyPath);
		if (!parsed.ok) {
			diagnostics.push({ file: policyPath, level: "error", message: `JSON 解析失败: ${parsed.error};回退默认` });
		} else {
			const merged = mergePolicy(DEFAULT_POLICY_CONFIG, parsed.value);
			if (policyValidator.Check(merged)) {
				policy = merged;
			} else {
				diagnostics.push({
					file: policyPath,
					level: "error",
					message: `schema 不符: ${formatErrors(policyValidator, merged)};回退默认`,
				});
			}
		}
	}

	// --- project-profile.json (optional; C1's init creates it) ---
	let profile: ProjectProfile | null = null;
	const profilePath = join(dir, "project-profile.json");
	if (existsSync(profilePath)) {
		const parsed = readJson(profilePath);
		if (!parsed.ok) {
			diagnostics.push({ file: profilePath, level: "error", message: `JSON 解析失败: ${parsed.error}` });
		} else if (isProfileLike(parsed.value)) {
			profile = parsed.value as ProjectProfile;
		} else {
			diagnostics.push({
				file: profilePath,
				level: "error",
				message: "schema 不符: 缺少必填字段 language 或 packageManager",
			});
		}
	}

	// --- memory.md ---
	let memory = "";
	const memoryPath = join(dir, "memory.md");
	if (existsSync(memoryPath)) {
		try {
			memory = readFileSync(memoryPath, "utf8");
		} catch (err) {
			const message = err instanceof Error ? err.message : String(err);
			diagnostics.push({ file: memoryPath, level: "warn", message: `读取失败: ${message}` });
		}
	}

	return { policy, profile, memory, diagnostics };
}
